CREATE TABLE IF NOT EXISTS "Users" (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myinfoapp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO myinfoapp;
